# Generated by Django 5.1.1 on 2026-01-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_user_id', models.CharField(help_text='eBay 平台上的唯一用户标识 (如 eIAS Token 或用户名)', max_length=255, unique=True, verbose_name='eBay 用户 ID')),
                ('ebay_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='eBay 用户名')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Token 过期时间')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20, verbose_name='环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='授权此 eBay 账户的 ERP 用户', on_delete=django.db.models.deletion.CASCADE, related_name='ebay_accounts', to=settings.AUTH_USER_MODEL, verbose_name='关联系统用户')),
            ],
            options={
                'verbose_name': 'eBay 账户',
                'verbose_name_plural': 'eBay 账户',
                'ordering': ['-created_at'],
            },
        ),
    ]
