# Generated by Django 6.0 on 2025-12-10 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="操作人"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "target_app",
                    models.CharField(max_length=64, verbose_name="目标应用"),
                ),
                (
                    "target_model",
                    models.CharField(max_length=64, verbose_name="目标模型"),
                ),
                ("target_id", models.CharField(max_length=64, verbose_name="目标ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "创建"),
                            ("UPDATE", "更新"),
                            ("DELETE", "删除"),
                        ],
                        max_length=10,
                        verbose_name="动作",
                    ),
                ),
                ("changes", models.JSONField(default=dict, verbose_name="变更详情")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="操作时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "System_Audit_Log_Django",
                "ordering": ["-timestamp"],
            },
        ),
    ]
