# Generated by Django 4.2.11 on 2025-12-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Trace ID')),
                ('patched_version', models.CharField(max_length=32, verbose_name='修复版本')),
                ('patched_at', models.DateTimeField(auto_now=True, verbose_name='标记时间')),
                ('patched_by', models.CharField(max_length=64, verbose_name='标记人')),
            ],
            options={
                'verbose_name': '故障修复状态',
                'verbose_name_plural': '故障修复状态',
                'db_table': 'System_Error_Patch_Status',
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='log_type',
            field=models.CharField(default='Regular', max_length=16, verbose_name='日志类型'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='root_cause',
            field=models.TextField(blank=True, null=True, verbose_name='失败根因'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(default='Success', max_length=32, verbose_name='状态'),
        ),
    ]
