# Generated by Django 5.1.1 on 2025-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_systemlogpatch_auditlog_log_type_auditlog_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='page_hierarchy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='页面层级'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ref_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='REF ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='snapshot_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='快照路径'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='underlying_data',
            field=models.JSONField(default=dict, verbose_name='底层数据'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', '查看页面'), ('QUERY', '查询数据'), ('MODIFY', '修改数据'), ('DELETE', '删除数据'), ('ADD', '新增数据'), ('QUERY_SET', '查询设置'), ('MODIFY_SET', '修改设置'), ('DELETE_SET', '删除设置'), ('ADD_SET', '新增设置'), ('START', '启动功能'), ('LOGIN', '登入'), ('LOGOUT', '登出'), ('PURGE', '清空日志'), ('ROLLBACK', '数据回滚'), ('GOD_MODE', '上帝模式'), ('LOCK', '锁定账户'), ('UNLOCK', '解锁账户'), ('PROMOTE', '提升权限'), ('DEMOTE', '降低权限')], max_length=32, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='root_cause',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='失败根因'),
        ),
    ]
