# Generated by Django 5.1.1 on 2025-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLock',
            fields=[
                ('resource_key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='资源Key')),
                ('locked_by', models.CharField(max_length=64, verbose_name='锁定人')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='锁定时间')),
                ('module_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '分布式锁',
                'verbose_name_plural': '分布式锁监控',
                'db_table': 'System_Locks',
                'managed': False,
            },
        ),
    ]
