# Generated by Django 5.1.1 on 2025-12-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(help_text='两个字母，不可重复', max_length=2, unique=True, verbose_name='供应商代号')),
                ('category', models.CharField(choices=[('E', '汽配'), ('A', '亚马逊')], help_text='E=汽配, A=亚马逊', max_length=1, verbose_name='供应商类别')),
                ('currency', models.CharField(choices=[('RMB', 'RMB'), ('USD', 'USD')], max_length=3, verbose_name='收货货币')),
                ('float_currency', models.BooleanField(default=False, verbose_name='货币是否浮动')),
                ('float_threshold', models.FloatField(default=0.0, help_text='汇率波动超过此值触发浮动规则', verbose_name='浮动阈值')),
                ('depository', models.BooleanField(default=False, verbose_name='是否需要定金')),
                ('deposit_par', models.FloatField(default=0.0, help_text='0-100', verbose_name='定金百分比')),
                ('status', models.BooleanField(default=True, help_text='True=Active, False=Inactive', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商管理',
                'db_table': 'in_supplier',
            },
        ),
    ]
