# Generated by Django 5.1.1 on 2025-12-19 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deposit_par',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='depository',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='float_currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='float_threshold',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(default='Default', help_text='请输入供货商名字', max_length=100, verbose_name='供应商名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SupplierStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', '汽配'), ('A', '亚马逊')], help_text='E=汽配, A=亚马逊', max_length=1, verbose_name='供应商类别')),
                ('currency', models.CharField(choices=[('RMB', 'RMB'), ('USD', 'USD')], max_length=3, verbose_name='收货货币')),
                ('float_currency', models.BooleanField(default=False, verbose_name='货币是否浮动')),
                ('float_threshold', models.FloatField(default=0.0, help_text='汇率波动超过此值触发浮动规则 (0-10%)', verbose_name='浮动阈值')),
                ('depository', models.BooleanField(default=False, verbose_name='是否需要定金')),
                ('deposit_par', models.FloatField(default=0.0, help_text='0-100', verbose_name='定金百分比')),
                ('status', models.BooleanField(default=True, help_text='True=Active, False=Inactive', verbose_name='状态')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效日期')),
                ('note', models.TextField(blank=True, default='默认策略', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(db_column='supplier_code', on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier', to_field='supplier_code', verbose_name='供应商代号')),
            ],
            options={
                'verbose_name': '供应商策略',
                'verbose_name_plural': '供应商策略管理',
                'db_table': 'in_supplier_strategy',
            },
        ),
    ]
