# Generated by Django 5.1.1 on 2025-12-19 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_supplier_category_remove_supplier_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstrategy',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生效日期'),
        ),
    ]
