# Generated by Django 5.1.1 on 2025-12-19 21:54

import backend.apps.purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_supplierstrategy_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstrategy',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to=backend.apps.purchase.models.SupplierStrategy.contract_upload_path, verbose_name='合同文件'),
        ),
    ]
