# Generated by Django 6.0 on 2026-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_supplierstrategy_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstrategy',
            name='by',
            field=models.CharField(blank=True, default='system', max_length=50, verbose_name='操作人'),
        ),
    ]
