# Generated by Django 6.0 on 2026-01-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_add_by_to_supplier_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstrategy',
            name='type',
            field=models.CharField(blank=True, choices=[('A', '电商货物供应商'), ('B', '货物依赖品供应商'), ('C', '耗材和其他供应商')], help_text='A=电商货物, B=货物依赖品, C=耗材和其他', max_length=1, null=True, verbose_name='供应商种类'),
        ),
    ]
